### ISSUE TITLE
Replace Pylint with ruff

### ISSUE THREAD

**Issue by timweiland** [marvinpfoertner/linpde-gp#36]
What do you think about replacing Pylint with [ruff](https://github.com/astral-sh/ruff)?

It's brutally fast compared to Pylint. On my machine it can lint the entire codebase in a fraction of a second.
This would speed up development - on the one hand, it would make the PR actions run through faster, and on the other hand, it's so fast that we might as well set up a pre-commit hook for it.

**Comment by marvinpfoertner** [comment]
As discussed offline, for me personally, the costs outweigh the benefits.
That being said, I'm not against it.
For me it would be important that the linter is about on par with the feature set of pylint.
